steps:
- name: sharescape/hasura-cli-docker
  id: "status"
  waitFor: ['-']
  env:
  - 'HASURA_GRAPHQL_SERVER_HOST=$_HASURA_GRAPHQL_SERVER_HOST'
  - 'HASURA_GRAPHQL_ADMIN_SECRET=$_HASURA_GRAPHQL_ADMIN_SECRET'
  - 'HASURA_GRAPHQL_ENV_FILE=$_HASURA_GRAPHQL_ENV_FILE'
  args: [ 'migrate', "status" ]

- name: sharescape/hasura-cli-docker
  id: "migrate"
  waitFor: ['status']
  env:
  - 'HASURA_GRAPHQL_SERVER_HOST=$_HASURA_GRAPHQL_SERVER_HOST'
  - 'HASURA_GRAPHQL_ADMIN_SECRET=$_HASURA_GRAPHQL_ADMIN_SECRET'
  - 'HASURA_GRAPHQL_ENV_FILE=$_HASURA_GRAPHQL_ENV_FILE'
  args: [ 'migrate', "apply" ]

- name: sharescape/hasura-cli-docker
  id: "metadata"
  waitFor: ['migrate']
  env:
  - 'HASURA_GRAPHQL_SERVER_HOST=$_HASURA_GRAPHQL_SERVER_HOST'
  - 'HASURA_GRAPHQL_ADMIN_SECRET=$_HASURA_GRAPHQL_ADMIN_SECRET'
  - 'HASURA_GRAPHQL_ENV_FILE=$_HASURA_GRAPHQL_ENV_FILE'
  args: [ "metadata", "apply" ]

substitutions:
  _HASURA_GRAPHQL_SERVER_HOST: ""
  _HASURA_GRAPHQL_ADMIN_SECRET: ""
  _HASURA_GRAPHQL_ENV_FILE: ""
